server:
  port: ${PORT:8082}

spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://mysql-16d7d2a7-omkardhepe007-1a69.d.aivencloud.com:11560/defaultdb?sslMode=REQUIRED&allowPublicKeyRetrieval=true&useSSL=true}
    username: ${DB_USERNAME:avnadmin}
    password: ${DB_PASSWORD:AVNS_wT_DhMvl_ToVmvTDyz7}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.MySQL8Dialect

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
